version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
    overwrite: true
hooks:
  BeforeInstall:
     - location: /scripts/install.sh
       timeout: 300
       runas: root
  ApplicationStop:
     - location: /scripts/stop.sh
       timeout: 300
       runas: root
