version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
     - location: Scripts/install
       timeout: 300
       runas: root
  ApplicationStop:
     - location: scripts/stop
       timeout: 300
       runas: root
